
package com.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://www.service.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.service.com", className = "com.service.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.service.com", className = "com.service.RegisterResponse")
    @Action(input = "http://www.service.com/WebService/registerRequest", output = "http://www.service.com/WebService/registerResponse")
    public boolean register(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clear", targetNamespace = "http://www.service.com", className = "com.service.Clear")
    @ResponseWrapper(localName = "clearResponse", targetNamespace = "http://www.service.com", className = "com.service.ClearResponse")
    @Action(input = "http://www.service.com/WebService/clearRequest", output = "http://www.service.com/WebService/clearResponse")
    public boolean clear(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://www.service.com", className = "com.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://www.service.com", className = "com.service.DeleteResponse")
    @Action(input = "http://www.service.com/WebService/deleteRequest", output = "http://www.service.com/WebService/deleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProject", targetNamespace = "http://www.service.com", className = "com.service.AddProject")
    @ResponseWrapper(localName = "addProjectResponse", targetNamespace = "http://www.service.com", className = "com.service.AddProjectResponse")
    @Action(input = "http://www.service.com/WebService/addProjectRequest", output = "http://www.service.com/WebService/addProjectResponse")
    public boolean addProject(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Project arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.service.Project>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchProject", targetNamespace = "http://www.service.com", className = "com.service.SearchProject")
    @ResponseWrapper(localName = "searchProjectResponse", targetNamespace = "http://www.service.com", className = "com.service.SearchProjectResponse")
    @Action(input = "http://www.service.com/WebService/searchProjectRequest", output = "http://www.service.com/WebService/searchProjectResponse")
    public List<Project> searchProject(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userExist", targetNamespace = "http://www.service.com", className = "com.service.UserExist")
    @ResponseWrapper(localName = "userExistResponse", targetNamespace = "http://www.service.com", className = "com.service.UserExistResponse")
    @Action(input = "http://www.service.com/WebService/userExistRequest", output = "http://www.service.com/WebService/userExistResponse")
    public boolean userExist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
